---
title: "Data Manipulation - Data Wrangling I"
date: September 18th, 2025
output: github_document
---

```{r}
library(tidyverse)
```

## Load in the Litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## let's take a look at `select`. This helps chose some columns and not others

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

Renaming columns ...

```{r}
select(litters_df, GROUP = group, LITTer_NUmBeR = litter_number)
```

```{r}
rename(litters_df,GROUP = group, LITTer_NUmBeR = litter_number)
```

Select helpers

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

## `filter` --> this operates on rows. It also filters rows based on observations/conditionsm and also logical operators

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

== -> text for equality

```{r}
filter(litters_df, gd_of_birth == 20)
```

! gives me the rows that are not equal to 20

```{r}
filter(litters_df, gd_of_birth != 20)
```

Working with two conditions

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group =="Con7")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8"))
```


