---
title: "Tidy Data - Data Wrangling I"
date: September 23rd, 2025
output: github_document
---

```{r}
library(tidyverse)
```

## let's take a look to `pivot_longer`

```{r}
pulse_data =
  haven::read_sas("./data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names()
```

Let's now go from wide format to long format

```{r}
pulse_data_tidy =
  pulse_data |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )
```

Let's rewrite, combine, and extend to add a mutate

```{r}
pulse_data =
  haven::read_sas("./data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) |> 
  relocate(id, visit) |> 
  mutate(visit = recode(visit, "bl" = "00m"))

```

## Let's now work on `pivot_wider`

```{r}
analysis_result =
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result |> 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )
```

## Let's now work on binding rows. We're going to use the LotR dataset. The first step is import each table

```{r}
fellowship_ring =
readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |> 
  mutate(movie = "fellowship_ring")

two_towers =
readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |> 
  mutate(movie = "two_towers")

return_king =
readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |> 
  mutate(movie = "return_king")
```

Let's bind all the rows together

```{r}
lotr_tidy =
  bind_rows(fellowship_ring, two_towers, return_king) |> 
  janitor::clean_names() |> 
  relocate(movie) |> 
  pivot_longer(
    female:male, names_to = "gender",
    values_to = "words"
  )
```

## let's focus on joining datasets

Import an clean the FAS datasets

```{r}
pups_df =
  read_csv("./data/FAS_pups.csv", skip = 3) |> 
  janitor::clean_names() |> 
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))

litters_df =
  read_csv("./data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  relocate(litter_number) |> 
  separate(group, into = c("dose", "day_of_tx"), sep = 3)
```

Let's now join them

```{r}
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") |> 
  arrange(litter_number) |> 
  relocate(litter_number, dose, day_of_tx)
```

